export { configKey, useConfig } from '../../../app-core/useConfig'
export { acServiceKey, acUseService } from './useService'
export { routerKey, useRouter } from '../../../app-core/useRouter'
export { getToken, setToken, getUserInfo, setUserInfo } from '../../../app-core/authentication'
export { navigateBack } from '../../../app-core/navigate'
export { default as router } from '../../../app-core/router'
export { default as createCore } from '../../../app-core/createCore'

export type { ComponentCustomProperties } from '../../../app-core/createCore'
export type { UserInfo } from '../../../app-core/authentication'
